namespace Postmaster.Dashboard
{
    /// <summary>
    /// Configuration options for the Postmaster dashboard middleware.
    /// </summary>
    public class DashboardOptions
    {
        /// <summary>
        /// Username for HTTP Basic authentication. When <c>null</c>, the dashboard is accessible without authentication.
        /// </summary>
        public string? Username { get; set; }

        /// <summary>
        /// Password for HTTP Basic authentication.
        /// </summary>
        public string? Password { get; set; }

        /// <summary>
        /// Optional path base when the application is hosted behind a reverse proxy or gateway with a URL prefix.
        /// For example, if your app is accessible at <c>https://example.com/myapp/</c>, set this to <c>"/myapp"</c>.
        /// This prefix is prepended to all asset and API URLs generated by the dashboard.
        /// </summary>
        public string? PathBase { get; set; }
    }
}
